Style bug fix
Vikleoboy/book-reader-website pull request #10
Opened 2024-07-17 00:10 UTC by RajiAujla

### Description

This pull request fixes a bug related to fixing navigation menu in the header section on mobile device and contibution section aligment fix.

Fixes #9 (make the website mobile responsive , just some bugs)

### Type of Change

Bug Fix

- Adjusted the CSS for the navigation menu to ensure proper alignment on mobile devices.
- Contribution section content layout fix to handle different sizes more effectively.
- image adjustment to fix the border size on alter screen size.

### How Has This Been Tested?

- Tested on various devices (iPhone 12 Pro, Samsung Galaxy S8+) to ensure the navigation menu and   section adjustment is aligned correctly.
- Used browser developer tools to simulate different screen sizes and verify the changes.
- Ran the full test suite to ensure no existing functionality is broken.

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### Screenshots:

After Fix:
![navbar](https://github.com/user-attachments/assets/bc28fbd6-4660-495e-8d6d-093b613cc019)
![contribution section](https://github.com/user-attachments/assets/59e21b98-649d-4df6-9510-6e74d71e6a54)

2024-07-17 13:40 UTC, Vikleoboy commented
![image](https://github.com/user-attachments/assets/7325202b-995c-456a-8110-84add2fde032)
## Task 1
The button is really close to the image. Please adjust the spacing to create some distance between them. This issue only occurs with specific dimensions that are in the picture .

## Task 2
![image](https://github.com/user-attachments/assets/b67f35ee-6d36-4e29-a008-8dc7dce220ee)

Also, reduce the font size for mobile devices to improve readability.

2024-07-17 13:45 UTC, Vikleoboy requested changes

2024-07-17 13:45 UTC, Vikleoboy commented on components/Navbar.tsx
> +      <section className="navsize:hidden flex  justify-between items-baseline pt-4 pb-4 px-4 w-full  z-50">
the text on mobile navbar only says Axiom Make it Axiom books and change its coulor to black plz

2024-07-18 02:20 UTC, RajiAujla commented
Task and Task 2 has fixed and updated.
Also, the extra space between the sections has been remove and at the end footer bottom padding adjusted too.

2024-07-18 04:34 UTC, merged

2024-07-18 04:36 UTC, Vikleoboy commented
Oh soory i merged this but we actully need the space betwwen sections so put back the h-100vh